import { Product } from './types';

export const allCategories = [
  "Durga Puja Specials",
  "Pujor Shaj & Apparel",
  "Aarti & Dhunuchi Fragrance",
  "Mandir & Home Decor",
  "Festive Gifting & Sweets",
  "Smartphones & Accessories",
  "Computers & Laptops",
  "Audio & Headphones",
  "Wearable Technology",
  "Men's Fashion",
  "Women's Fashion",
  "Footwear",
  "Accessories",
  "Home Decor",
  "Kitchen & Dining",
  "Home & Kitchen",
  "Workspace",
  "Living"
];

export const products: Product[] = [
  {
    id: 'pujo-1',
    name: 'Pure Brass Aarti Dhunuchi with Hand-carved Handle',
    description: 'Traditional heavy brass Dhunuchi for Sandhi Puja aarti and Dhunuchi Naach. Features delicate perforations and heat-resistant fluted grip.',
    price: '₹2,499',
    mrp: '₹3,999',
    discount: '37%',
    imageUrl: 'https://images.unsplash.com/photo-1606293926075-69a00dbfde81?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/pujo-1',
    category: 'Aarti & Dhunuchi Fragrance',
    imageBgColor: 'bg-[#FFFBEB]',
    rating: 4.9,
    type: 'buy',
    festiveTag: 'Ashtami Essential',
    pujoDay: 'Ashtami'
  },
  {
    id: 'pujo-2',
    name: 'Heritage Gorod Silk Lal-Paar Festive Kurta & Stole',
    description: 'Woven with raw mulberry silk in off-white with vermilion red temple border. The timeless attire for Ashtami Anjali and Dashami Sindoor Khela.',
    price: '₹7,999',
    mrp: '₹11,999',
    discount: '33%',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/pujo-2',
    category: 'Pujor Shaj & Apparel',
    imageBgColor: 'bg-[#FEF2F2]',
    rating: 5.0,
    type: 'buy',
    hasSizes: true,
    festiveTag: 'Pujo Special',
    pujoDay: 'Ashtami'
  },
  {
    id: 'pujo-3',
    name: 'Shiuli & Sandalwood Temple Diffuser with Terracotta Base',
    description: 'Infuse your home with the divine aroma of autumn Shiuli (night-blooming jasmine) and Mysore chandan — the nostalgic scent of Pujo mornings.',
    price: '₹1,899',
    mrp: '₹2,699',
    discount: '30%',
    imageUrl: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/pujo-3',
    category: 'Aarti & Dhunuchi Fragrance',
    imageBgColor: 'bg-[#FFFDF5]',
    rating: 4.8,
    type: 'buy',
    festiveTag: 'Autumn Agomoni',
    pujoDay: 'Shasthi'
  },
  {
    id: 'pujo-4',
    name: 'Handcrafted Alpona Motif Brass Thali & Diya Set',
    description: 'Etched with traditional Bengali lotus and paisley Alpona floor-art patterns. Includes 5 auspicious Panchapradeep diyas and a sandalwood cup.',
    price: '₹3,299',
    mrp: '₹4,599',
    discount: '28%',
    imageUrl: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/pujo-4',
    category: 'Mandir & Home Decor',
    imageBgColor: 'bg-[#FEFCE8]',
    rating: 4.9,
    type: 'buy',
    festiveTag: 'Puja Rituals',
    pujoDay: 'Saptami'
  },
  {
    id: 'pujo-5',
    name: 'Royal Bengali Handloom Cotton Jamdani Saree & Scarf',
    description: 'Intricately handwoven with fine floral jaal motifs on featherlight muslin cotton. Breathable elegance for morning pandal hopping.',
    price: '₹5,899',
    mrp: '₹8,499',
    discount: '31%',
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/pujo-5',
    category: 'Pujor Shaj & Apparel',
    imageBgColor: 'bg-[#FFF7ED]',
    rating: 4.9,
    type: 'buy',
    festiveTag: 'Pujor Notun Shaj',
    pujoDay: 'Saptami'
  },
  {
    id: 'pujo-6',
    name: 'Artisan Sandesh & Dry Fruit Festive Gift Box',
    description: 'A luxurious keepsake brass-embossed box filled with traditional artisanal confections, saffron almonds, and Subho Bijoya festive greetings.',
    price: '₹2,199',
    mrp: '₹2,999',
    discount: '26%',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/pujo-6',
    category: 'Festive Gifting & Sweets',
    imageBgColor: 'bg-[#FFFBEB]',
    rating: 5.0,
    type: 'buy',
    festiveTag: 'Bijoya Special',
    pujoDay: 'Dashami'
  },
  {
    id: '1',
    name: 'Ceramic Pour-Over Kettle',
    description: 'Matte finish with a precision spout for the perfect morning ritual.',
    price: '₹5,499',
    mrp: '₹7,999',
    discount: '31%',
    imageUrl: 'https://images.unsplash.com/photo-1544004481-7998634d008d?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/1',
    category: 'Home & Kitchen',
    imageBgColor: 'bg-[#F4F1EE]',
    rating: 4.8
  },
  {
    id: '2',
    name: 'Minimalist Desk Lamp',
    description: 'Soft ambient lighting with adjustable brightness for deep focus.',
    price: '₹9,999',
    mrp: '₹14,999',
    discount: '33%',
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/2',
    category: 'Workspace',
    imageBgColor: 'bg-[#EFF2F0]',
    rating: 4.5
  },
  {
    id: '3',
    name: 'Linen Throw Blanket',
    description: 'Breathable, ultra-soft organic linen for year-round comfort.',
    price: '₹6,999',
    mrp: '₹8,999',
    discount: '22%',
    imageUrl: 'https://images.unsplash.com/photo-1580870059815-5633e72eb178?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/3',
    category: 'Living',
    imageBgColor: 'bg-[#F3EFEA]',
    rating: 5
  },
  {
    id: '4',
    name: 'Leather Notebook Folio',
    description: 'Handcrafted full-grain leather to protect your thoughts and ideas.',
    price: '₹3,499',
    mrp: '₹4,999',
    discount: '30%',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/4',
    category: 'Accessories',
    imageBgColor: 'bg-[#EAECEF]',
    rating: 4.9
  },
  {
    id: '5',
    name: 'Acoustic Desk Partition',
    description: 'Reduce noise and visual distractions in open spaces effortlessly.',
    price: '₹15,999',
    mrp: '₹19,999',
    discount: '20%',
    imageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/5',
    category: 'Workspace',
    imageBgColor: 'bg-[#F0EBE6]',
    rating: 4.7
  },
  {
    id: '6',
    name: 'Stoneware Mug Set',
    description: 'Set of two handmade mugs, glazed in a soft, earthy tone.',
    price: '₹2,999',
    mrp: '₹3,999',
    discount: '25%',
    imageUrl: 'https://images.unsplash.com/photo-1610738038706-c87d4637da8c?q=80&w=800&auto=format&fit=crop',
    affiliateUrl: 'https://example.com/affiliate/6',
    category: 'Home & Kitchen',
    imageBgColor: 'bg-[#EBF0EF]',
    rating: 4.6
  }
];
